Features/url base localization
opc-cpvp/OfficeEntry pull request #58
Opened 2020-09-03 15:05 UTC by plbonneville

2020-09-04 12:26 UTC, pierluc-ssoucy requested changes
Two other similar item I was not sure where to put, and not sure if it's caused by localized routes or by authorization redirects but for both "approval pages" it seems to get stuck on the root splash page after you accept/finish the below:
- [ ] Health and safety measures
- [ ] Privacy Act Statement

2020-09-10 02:34 UTC, plbonneville commented on src/WebApp/Shared/NavMenu.razor
> +                @Localizer["LanguageToggle"]
Agreed.

2020-09-10 02:34 UTC, plbonneville commented on src/WebApp/Pages/Index.razor.cs
> +        protected override void OnInitialized()
They have been removed.

2020-09-10 02:42 UTC, merged

2020-09-10 12:12 UTC, pierluc-ssoucy commented
@plbonneville we you able to fix the "redirect bug" mentioned in the global comment?